# Support python 3.7: https://github.com/travis-ci/travis-ci/issues/9831
language: python
python: 3.7
dist: xenial
sudo: true
install:
  - make travis
script:
  - make test
  - make cover
  - make lint
