keys:
  key1: 'GOOGLESPREADSHEETIDXXXXXXXXXXXXXXXXXXXXXXXXX'
  key2: 'GOOGLESPREADSHEETIDXXXXXXXXXXXXXXXXXXXXXXXXX'
gmail:
  user: 'sample@example.com'
  password: 'XXXXXXXXXXXXXX'
auth:
  type: 'service_account'
  project_id: 'XXXXXXXXXXXXXXXXXXXXXX'
  private_key_id: 'XXXXXXXXXXXXX'
  private_key: '-----BEGIN PRIVATE KEY-----XXXXX-----END PRIVATE KEY-----\n'
  client_email: 'XXXX@XXXX'
  client_id: 'XXXXXXXXX'
  auth_uri: 'https://accounts.google.com/o/oauth2/auth'
  token_uri: 'https://accounts.google.com/o/oauth2/token'
  auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'
  client_x509_cert_url: 'https://www.googleapis.com/robot/v1/metadata/x509/XXXXXXXXX'
